// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarEchars: typeof import('./../components/Echars/BarEchars.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Echarts: typeof import('./../components/Echarts.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
