// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarEchars: typeof import('./../components/Echars/BarEchars.vue')['default']
    Echarts: typeof import('./../components/Echarts.vue')['default']
    ETitle: typeof import('./../components/ETitle.vue')['default']
    HorizontalEcharts: typeof import('./../components/Echars/HorizontalEcharts.vue')['default']
    MapEchars: typeof import('./../components/Echars/MapEchars.vue')['default']
    PieEchars: typeof import('./../components/Echars/PieEchars.vue')['default']
    RadarEchars: typeof import('./../components/Echars/RadarEchars.vue')['default']
  }
}
